name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag microdocsearch:latest
        docker save microdocsearch:latest -o microdocsearch.tar
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: microdocsearch
        path: microdocsearch.tar
